### ISSUE TITLE
Etherscan links incorrectly generated for mainnet streams review

### ISSUE THREAD

**Issue by dasanra** [sablierhq/safe-app#100]
###  Overview
Etherscan mainnet link is getting wrong domain to create the link, pointing to an unexistant domain.

https://github.com/sablierhq/safe-app/blob/a3812e27a61631f6ac8b76d416dca96cd6022689/src/components/EtherscanLink/Buttons/EtherscanButton.tsx#L27

### Expected

Correct mainnet etherscan link 
`https://etherscan.io/`

**Comment by maxdesalle** [comment]
Thank you for reporting this issue! Fixed in [0fb2382](https://github.com/sablierhq/safe-app/commit/0fb23829263d045a6d3a001babe6aa99a140e1b3).
