### ISSUE TITLE
Handle the case where the network is different

### ISSUE THREAD

**Issue by PaulRBerg** [sablierhq/safe-app#18]
I'm not sure if we have to fix this at all. Maybe the fact that the app is intended to be run under an inframe on the Gnosis websites makes this a non-issue.

The error I get when MetaMask is set to a network other than Mainnet or Rinkeby:

<img width="410" alt="Capture d’écran 2020-05-31 à 19 45 04" src="https://user-images.githubusercontent.com/8782666/83357824-79e97480-a377-11ea-9835-c46db8018b65.png">

This is from my local development tree, not yet pushed to origin.

**Comment by TomAFrench** [comment]
Yeah, the network is injected by Gnosis through the `safeInfo` object and as far as I know they only run on mainnet and rinkeby.
